### ISSUE TITLE
Cannot import interfaces

### ISSUE THREAD

**Issue by kokiebisu** [slackapi/node-slack-sdk#1293] opened 2021-07-23 04:27 UTC
### Description

I get a 'Module '"@slack/web-api"' has no exported member 'Channel'' error on VSCode. I'm not sure if this is a bug.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version:
6.3.0
node version:
12.22.3
OS version(s):
macOS
#### Steps to reproduce:

1. try adding an import statement

```ts
import { Channel } from '@slack/web-api'
```
#### Expected result:

What you expected to happen
Should be importing the Channel interface without any problems

#### Actual result:

VSCode doesn't recognize the Channel interface

#### Attachments:

![スクリーンショット 2021-07-22 午後9 24 00](https://user-images.githubusercontent.com/43525282/126737414-642038a8-2c89-43d0-9ffe-8657230f7468.png)

**Comment by misscoded** [comment] 2021-07-24 17:21
Hi @kokiebisu! Thanks for raising this question. I can confirm that this is not a bug but rather an area of improvement that has yet to be addressed. 

As it stands today, we do not offer the level of type support for this package that you're seeking. With regard to `@slack/web-api` specifically, basic data elements like `Channel` can vary in shape across different endpoints and, though we've started down the path of auto-generated types, we've yet to continue that work to shore up the type deficiencies and provide the ability to selectively import interfaces as you've attempted to do so above.

As we've provided an answer, I'm going to close this issue, but we very much appreciate you submitting this issue and in turn providing us feedback that it'd be a valuable addition! 🙂

**Closed by misscoded** 2021-07-24 17:21 UTC
Labels: question
