### ISSUE TITLE
@slack/client:KeepAlive Unhandled error

### ISSUE THREAD

**Issue by gunslingerfry** [slackapi/node-slack-sdk#527] opened 2018-04-10 16:01 UTC
### Description

Receiving a web socket error within a few hours of starting an RTMClient connection. 

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [X] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [X] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

It has presented in two different ways.

[04/06/2018 12:24:07.008] [ERROR] [ERROR] @slack/client:RTMClient A websocket error occurred: read ECONNRESET
/home/matthew/chatbot/node_modules/@slack/client/dist/KeepAlive.js:104
                        throw errors_1.errorWithCode(new Error('no client found'), _1.ErrorCode.KeepAliveInconsistentState);
                        ^

Error: no client found
    at Timeout.setTimeout [as _onTimeout] (/home/matthew/chatbot/node_modules/@slack/client/dist/KeepAlive.js:104:54)
    at ontimeout (timers.js:478:11)
    at tryOnTimeout (timers.js:302:5)
    at Timer.listOnTimeout (timers.js:262:5)
rs

[04/09/2018 18:22:29.887] [ERROR] [ERROR] @slack/client:RTMClient failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING)
[04/09/2018 18:22:29.889] [ERROR] [ERROR] @slack/client:KeepAlive Unhandled error: Failed to send message on websocket: WebSocket is not open: readyState 2 (CLOSING). Please report to @slack/client package maintainers.

#### Reproducible in:

`@slack/client` version: 4.1.0

node version: 9.2.0

OS version(s): Ubuntu 16.04

#### Steps to reproduce:

1. I do not know. It doesn't seem to require much time (a couple hours) to reproduce, but it is just running the server. I migrated from v3 to v4 and did some clean up of my own code on the way but I do not see how this is related to my code.

#### Expected result:

Web socket remains open, as it did in v3.

#### Actual result:

Unhandled error.

#### Attachments:

```
// RTM is started this way
const { WebClient, RTMClient } = require('@slack/client');
const rtm = new RTMClient(token);
rtm.start();
rtm.on('message', (event) => {
 ... my code...
});

// There's also an http server which is listening for notifications from another server
var server = http.createServer( function (request, response) {
...my code...
}
server.listen(8000);

// I'm posting to Slack and using a few other API calls using the Web API
web.chat.postMessage({channel: options.channel, text: message, username: "JIRA Bot", icon_emoji: ":jira:"});

**Comment by aoberoi** [comment] 2018-04-13 00:46
@gunslingerfry thank you for reporting. it's difficult to know where to start here, but i will try to reproduce this issue and see if we can identify the cause. i think the biggest clue is the socket is in the closing state. if you wouldn't mind, since you're able to reproduce the issue, can you increase the `logLevel` in your code to debug and share the logs?

**Comment by gunslingerfry** [comment] 2018-04-13 16:53
Here's the output with the DEBUG logLevel.

```
[04/13/2018 10:51:17.546] [ERROR] [ERROR] @slack/client:RTMClient A websocket error occurred: Unexpected server response: 503
/home/matthew/chatbot/node_modules/finity/lib/core/StateMachine.js:76
      throw new Error('Unhandled event \'' + event + '\' in state \'' + this.currentState + '\'.');
      ^

Error: Unhandled event 'websocket close' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/home/matthew/chatbot/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /home/matthew/chatbot/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/home/matthew/chatbot/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/home/matthew/chatbot/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/home/matthew/chatbot/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at WebSocket.websocket.addEventListener.event (/home/matthew/chatbot/node_modules/@slack/client/dist/RTMClient.js:375:77)
    at WebSocket.onClose (/home/matthew/chatbot/node_modules/ws/lib/event-target.js:124:16)
    at WebSocket.emit (events.js:159:13)
    at WebSocket.finalize (/home/matthew/chatbot/node_modules/ws/lib/websocket.js:187:12)
    at ClientRequest._req.on (/home/matthew/chatbot/node_modules/ws/lib/websocket.js:641:12)
```

**Comment by aoberoi** [comment] 2018-04-18 23:10
@gunslingerfry thanks for the stacktrace. the most valuable bit i see is `A websocket error occurred: Unexpected server response: 503`. i'm going to look into what the possible causes of that are, and how we can anticipate and handle it properly.

can you show us what was occurring in the logs before that point? i'm trying to determine which state each of the objects were in so i can trace or reproduce the issue. please redact anything that is sensitive to your app/users.

at this point this issue seems identical to #531, so i'm going to close this one as a duplicate. the only reason i'm choosing that one is because it has more logs.

**Closed** 2018-04-18 23:10 UTC
Labels: duplicate

**Comment by aoberoi** [comment] 2018-05-01 15:37
@gunslingerfry have you tried v4.2.0? Any better than the previous version? At the very least we should have more meaningful logging.

**Comment by gunslingerfry** [comment] 2018-05-01 15:44
I'll update and get back to you.

**Comment by ghadaezzat** [comment] 2018-05-12 14:34
i tried v4.2 and the problem still exists

**Comment by gunslingerfry** [comment] 2018-05-17 22:05
Problem still exists.

**Comment by gunslingerfry** [comment] 2018-05-18 16:51
I've just moved back to v3 because I know it's reliable. I can't seem to find the correct magic in nodemon / forever to get my bot back up and running when it crashes.

**Comment by aoberoi** [comment] 2018-05-18 17:52
@gunslingerfry i'm sorry you have to make such a radical jump. we have a fix on master that's i can release today. if i get that out in the next couple hours, would that be helpful?

**Comment by gunslingerfry** [comment] 2018-05-18 20:14
Might have seen this too late, but yeah that would be great.

**Comment by bmajz** [comment] 2018-06-05 06:19
I saw something that looks related on 4.2.2. This caused an unhandled exception that took down the whole worker unfortunately :(

```
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      | Error: no client found
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at KeepAlive.attemptAcknowledgePong (/home/node_modules/@slack/client/dist/KeepAlive.js:92:54)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at RTMClient.emit (/home/node_modules/eventemitter3/index.js:182:35)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at RTMClient.onWebsocketMessage (/home/node_modules/@slack/client/dist/RTMClient.js:463:14)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at WebSocket.onMessage (/home/node_modules/ws/lib/event-target.js:120:16)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at emitOne (events.js:96:13)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at WebSocket.emit (events.js:188:7)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at Receiver._receiver.onmessage (/home/node_modules/ws/lib/websocket.js:137:47)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at Receiver.dataMessage (/home/node_modules/ws/lib/receiver.js:409:14)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at Receiver.getData (/home/node_modules/ws/lib/receiver.js:347:12)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at Receiver.startLoop (/home/node_modules/ws/lib/receiver.js:143:16)
Jun 04 07:25:28 a1c9e0384b32 ecs-rtmworker-19-rtmworker-c8f2d1adf5f7faeff301: 14:25:28 0|rtm      |     at Receiver.add (/home/node_modules/ws/lib/receiver.js:117:10) 
```

**Comment by bmajz** [comment] 2018-06-05 06:21
I have numerous repros of the above and I occasionally see them prefaced with something like this:
[ERROR] @slack/client:RTMClient A websocket error occurred: read ECONNRESET

**Comment by sandro-pasquali** [comment] 2018-06-05 11:03
This happens pretty regularly for me, as described by @gunslingerfry. In my case I'm running it locally (off my local box) and I *think* it's happening when my box goes to sleep/turns off its connection. Maybe a subscribable online/offline check for the client?

**Comment by bmajz** [comment] 2018-06-05 11:32
Yeah — just wanted to point out the version number. In my case this is not a machine that’s going down — happening in an always on cloud environment.
