### ISSUE TITLE
Handle a token revocation by user (Manage app)

### ISSUE THREAD

**Issue by DominikPalo** [slackapi/node-slack-sdk#367] opened 2017-06-22 12:08 UTC
RTM client: I didn't find a good way how to handle a situation when a user revokes an app token from the app settings page under the Manage apps (using the trash button near his name or by clicking on the Remove App button). In this case, the RTM client fails with an error:
```
error: Response not OK:  account_inactive
error: Disconnecting because account_inactive is not recoverable
error:  Error: account_inactive
    at handleHttpResponse...
```

I registered a handler for the `CLIENT_EVENTS.RTM.DISCONNECT`:

```
this.slackBot.on(SlackClient.CLIENT_EVENTS.RTM.DISCONNECT, (reason) => {
  if (reason === 'account_inactive is not recoverable') {
    // handle unistallation properly
  }
});`
```

But this is not a very nice solution and also it's not possible to catch internal error thrown by `handleHttpResponse` in `call-transport.js` so it fills my node.js error logs.

**Comment by aoberoi** [comment] 2017-06-22 18:21
hi @DominikPalo, thanks for the feedback.

The RTM API isn't receiving many of the new enhancements the Slack Platform has to offer. We're encouraging most developers (outside specific use cases and scenarios) to use a combination of the Web API and [Events API](https://api.slack.com/events-api) instead.

In this case, the [`app_uninstalled`](https://api.slack.com/events/app_uninstalled) event is exactly what you want, and its exclusively part of the Events API. I recommend integrating our [Events API adapter](https://github.com/slackapi/node-slack-events-api) into your app and handling the scenario that way. (BTW, we welcome feedback on that module and its documentation too, its still pretty new!)

However, I am concerned about this:

> it's not possible to catch internal error thrown by handleHttpResponse in call-transport.js so it fills my node.js error logs.

Can you give me an example so I can reproduce this? `handleHttpResponse` is used by the `WebClient`, and all calls from that client either take a callback which should supply you with the error, or it returns a Promise, which should reject with the error.

Lastly, I'm curious about whether you've tried the Events API. do you have a scenario in which the RTM API is preferrable? one of the known ones are when you are behind a corporate firewall and cannot handle incoming connections, but I'm curious to find out other reasons our developers might not be moving to the Events API.

**Comment by DominikPalo** [comment] 2017-07-03 14:10
@aoberoi thank you for a detailed explanation. I know about pros of the Events API, but I need to stick with the RTM API for now because with the Event API it's not possible to simulate "typing indicator" `user_typing` (which we need to show in bot conversations). And error in the `handleHttpResponse` method is fired when my bot is trying to reconnect (after token was revoked).
```
warn: Reconnecting, on attempt 1
error: Response not OK:  account_inactive
error: Disconnecting because account_inactive is not recoverable
error:  Error: account_inactive...
```

**Comment by aoberoi** [comment] 2017-08-01 23:27
Great, thanks for the feedback about `user_typing`. We don't have any plans to port that into the Web API at the moment, so I think the best solution is to use the Events API in addition to the RTM API in your App.

As for the errors, I think we are talking about two different things: (1) the ability to programmatically handle the disconnection after a token is revoked, (2) the output on stdout that you have captured in your log files.

I think (1) is not an issue because you have code that can programmatically respond to this situation in your issue report. Let me know if there's something else you would have hoped for.

I think (2) can also be dealt with by setting options on the `RtmClient` instance. You can change the `logLevel` option to `0` (or `'error'`) to reduce the log messages to just those that are considered errors. In this case, that won't be enough to get rid of the lines you are seeing, so what you could do is pass a custom `logger` as an option for the `RtmClient` instance. You then get full control of what gets output, and you can even use a noop function if you want nothing output at all.

**Closed by aoberoi** 2017-08-01 23:27 UTC
