### ISSUE TITLE
Node.js app crashes abruptly (slack_webapi_platform_error) while in socket mode

### ISSUE THREAD

**Issue by cmorinupgrade** [slackapi/node-slack-sdk#1626] opened 2023-05-23 20:29 UTC
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [x] `@slack/logger`
- [x] `@slack/oauth`
- [x] `@slack/socket-mode`
- [x] `@slack/types`

#### The Slack SDK version

3.12.2

#### Node.js runtime version

16.19.1

#### OS info

Running in Kubernetes (amazonlinux `2023.0.20230322.0`)

#### Steps to reproduce:

Simply have the app running and then when an outage happens on Slack API side, while in socket mode, the app crashes/terminates. 

### Expected result:

Gracefully terminate the socket, and have the ability to handle the error on the client side. Would also be neat to have a retry mechanism in place.

### Actual result:

Crashes abruptly with the following error:

```
/app/node_modules/@slack/web-api/dist/errors.js:56
    const error = errorWithCode(new Error(`An API error occurred: ${result.error}`), ErrorCode.PlatformError);
                                ^

Error: An API error occurred: fatal_error
    at platformErrorFromResult (/app/node_modules/@slack/web-api/dist/errors.js:56:33)
    at WebClient.apiCall (/app/node_modules/@slack/web-api/dist/WebClient.js:181:56)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'fatal_error',
    response_metadata: {
      scopes: [
        'app_mentions:read',
        'chat:write',
        'im:history',
        'im:read',
        'im:write',
        'commands'
      ],
      acceptedScopes: [ 'chat:write' ]
    }
  }
}
error Command failed with exit code 1.
```

### Implementation

```
const app = new App({
    token: my_token,
    appToken: my_slack_app_token,
    signingSecret: secret,
    socketMode: true,
  });

  app.message(handler());
  app.event('app_mention', handle);

  await app.start();
```

**Comment by cmorinupgrade** [comment] 2023-05-24 17:53
This outage caused our node.js app to restart a couple times: https://status.slack.com/2023-05/f1df0cac8d8d8d68. 

Any Slack command trying to interact with the Slack API through socket mode terminated the application. The command execution themselves are try/catched.

**Comment by seratch** [comment] 2023-05-24 23:45
Hi @cmorinupgrade, thanks a lot for sharing this issue. My initial guess on the cause of the unhandled error is that SocketModeClient still misses some error handling patterns, but I haven't identified where and how we improve the code yet. Did you see any other logs when the process crash happened? Sharing as many information as possible would be greatly appreciated.

**Comment by cmorinupgrade** [comment] 2023-05-25 13:59
Hey @seratch , thanks for the quick response!

I just checked the logs and I see warnings as well:

`[WARN]  web-api:WebClient:0 Additionally, the attachment-level `fallback` argument is missing in the request payload for a chat.postMessage call - To avoid this warning, it is recommended to always provide a top-level `text` argument when posting a message. Alternatively, you can provide an attachment-level `fallback` argument, though this is now considered a legacy field (see https://api.slack.com/reference/messaging/attachments#legacy_fields for more details).`

Hope it helps

**Comment by filmaj** [comment] 2024-01-25 20:25
I do not think this is an issue w/ the latest `main`. I tried reproducing this using the `ws` package in node like so in a mocha test:

```javascript
const { assert } = require('chai');
const { SocketModeClient} = require('../src/SocketModeClient');
const { LogLevel } = require('../src/logger');
const { WebSocketServer} = require('ws');
const { createServer } = require('http');
const sinon = require('sinon');

const HTTP_PORT = 12345;
const WSS_PORT = 23456;
// Basic HTTP server to 'fake' behaviour of `apps.connections.open` endpoint
const server = createServer((req, res) => {
  res.writeHead(200, { 'content-type': 'application/json' });
  res.end(JSON.stringify({
    ok: true,
    url: `ws://localhost:${WSS_PORT}/`,
  }));
});

// Basic WS server to fake slack WS endpoint
let wss = null;
let exposed_ws_connection = null;

// Socket mode client pointing to the above two posers
let client = null;

describe('Integration tests with a WebSocket server', () => {
  beforeEach(() => {
    server.listen(HTTP_PORT);
    wss = new WebSocketServer({ port: WSS_PORT });
    wss.on('connection', (ws) => {
      ws.on('error', (err) => {
        assert.fail(err);
      });
      // Send `Event.ServerHello`
      ws.send(JSON.stringify({type: 'hello'}));
      exposed_ws_connection = ws;
    });
  });
  afterEach(() => {
    server.close();
    wss.close();
    exposed_ws_connection = null;
    client = null;
  });
  describe('catastrophic server behaviour', () => {
    beforeEach(() => {
      client = new SocketModeClient({ appToken: 'whatever', logLevel: LogLevel.DEBUG, clientOptions: {
        slackApiUrl: `http://localhost:${HTTP_PORT}/`
      }});
    });
    it.only('should gracefully handle a peer disconnect', async () => {
      await client.start();
      for (const client_connection of wss.clients) {
        console.log('terminating', client_connection);
        client_connection.terminate();
      }
      // wss.close();
      // await client.disconnect();
    });
  });
});
```

That yields the following (debug) logs:

```
  Integration tests with a WebSocket server
    catastrophic server behaviour
[DEBUG]  web-api:WebClient:0 initialized
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: disconnected
[DEBUG]  socket-mode:SocketModeClient:0 The Socket Mode client is successfully initialized
[DEBUG]  socket-mode:SocketModeClient:0 Starting a Socket Mode client ...
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:authenticating
[DEBUG]  socket-mode:SocketModeClient:0 Going to retrieve a new WSS URL ...
[DEBUG]  web-api:WebClient:0 apiCall('apps.connections.open') start
[DEBUG]  web-api:WebClient:0 http request url: http://localhost:12345/apps.connections.open
[DEBUG]  web-api:WebClient:0 http request body: {}
[DEBUG]  web-api:WebClient:0 http request headers: {}
[DEBUG]  web-api:WebClient:0 http response received
[DEBUG]  web-api:WebClient:0 http request result: {"ok":true,"url":"ws://localhost:23456/","response_metadata":{}}
[DEBUG]  web-api:WebClient:0 apiCall('apps.connections.open') end
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:authenticated
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:handshaking
[DEBUG]  socket-mode:SocketModeClient:0 Received a message on the WebSocket: {"type":"hello"}
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connected
[INFO]  socket-mode:SocketModeClient:0 Now connected to Slack
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connected:preparing
[DEBUG]  socket-mode:SocketModeClient:0 Started running a new heart beat job
terminating <ref *1> WebSocket { ... }
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connected:ready
      ✔ should gracefully handle a peer disconnect
[DEBUG]  socket-mode:SocketModeClient:0 Cancelled the job waiting for ping from Slack
[DEBUG]  socket-mode:SocketModeClient:0 Terminated the heart beat job
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: reconnecting
[INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting
[INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
[DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:authenticating
[DEBUG]  socket-mode:SocketModeClient:0 Going to retrieve a new WSS URL ...
[DEBUG]  web-api:WebClient:0 apiCall('apps.connections.open') start
[DEBUG]  web-api:WebClient:0 http request url: http://localhost:12345/apps.connections.open
[DEBUG]  web-api:WebClient:0 http request body: {}
[DEBUG]  web-api:WebClient:0 http request headers: {}

[WARN]  web-api:WebClient:0 http request failed connect ECONNREFUSED 127.0.0.1:12345

  1 passing (50ms)

[DEBUG]  web-api:WebClient:0 http request url: http://localhost:12345/apps.connections.open
[DEBUG]  web-api:WebClient:0 http request body: {}
[DEBUG]  web-api:WebClient:0 http request headers: {}
[WARN]  web-api:WebClient:0 http request failed connect ECONNREFUSED 127.0.0.1:12345
```

No crashes, though with the websocket peer being offline, it should be expected that this client tries to reconnect forever unsuccessfully.

I will continue with releasing the latest `main` as v2 of socket-mode and close this issue.

**Closed by filmaj** 2024-01-25 20:25 UTC
Labels: bug, pkg:web-api, pkg:socket-mode

**Comment by sergio-toro** [comment] 2024-03-07 14:39
> I do not think this is an issue w/ the latest `main`. I tried reproducing this using the `ws` package in node like so in a mocha test:
> 
> ```js
> const { assert } = require('chai');
> const { SocketModeClient} = require('../src/SocketModeClient');
> const { LogLevel } = require('../src/logger');
> const { WebSocketServer} = require('ws');
> const { createServer } = require('http');
> const sinon = require('sinon');
> 
> const HTTP_PORT = 12345;
> const WSS_PORT = 23456;
> // Basic HTTP server to 'fake' behaviour of `apps.connections.open` endpoint
> const server = createServer((req, res) => {
>   res.writeHead(200, { 'content-type': 'application/json' });
>   res.end(JSON.stringify({
>     ok: true,
>     url: `ws://localhost:${WSS_PORT}/`,
>   }));
> });
> 
> // Basic WS server to fake slack WS endpoint
> let wss = null;
> let exposed_ws_connection = null;
> 
> // Socket mode client pointing to the above two posers
> let client = null;
> 
> describe('Integration tests with a WebSocket server', () => {
>   beforeEach(() => {
>     server.listen(HTTP_PORT);
>     wss = new WebSocketServer({ port: WSS_PORT });
>     wss.on('connection', (ws) => {
>       ws.on('error', (err) => {
>         assert.fail(err);
>       });
>       // Send `Event.ServerHello`
>       ws.send(JSON.stringify({type: 'hello'}));
>       exposed_ws_connection = ws;
>     });
>   });
>   afterEach(() => {
>     server.close();
>     wss.close();
>     exposed_ws_connection = null;
>     client = null;
>   });
>   describe('catastrophic server behaviour', () => {
>     beforeEach(() => {
>       client = new SocketModeClient({ appToken: 'whatever', logLevel: LogLevel.DEBUG, clientOptions: {
>         slackApiUrl: `http://localhost:${HTTP_PORT}/`
>       }});
>     });
>     it.only('should gracefully handle a peer disconnect', async () => {
>       await client.start();
>       for (const client_connection of wss.clients) {
>         console.log('terminating', client_connection);
>         client_connection.terminate();
>       }
>       // wss.close();
>       // await client.disconnect();
>     });
>   });
> });
> ```
> 
> That yields the following (debug) logs:
> 
> ```
>   Integration tests with a WebSocket server
>     catastrophic server behaviour
> [DEBUG]  web-api:WebClient:0 initialized
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: disconnected
> [DEBUG]  socket-mode:SocketModeClient:0 The Socket Mode client is successfully initialized
> [DEBUG]  socket-mode:SocketModeClient:0 Starting a Socket Mode client ...
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting
> [INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:authenticating
> [DEBUG]  socket-mode:SocketModeClient:0 Going to retrieve a new WSS URL ...
> [DEBUG]  web-api:WebClient:0 apiCall('apps.connections.open') start
> [DEBUG]  web-api:WebClient:0 http request url: http://localhost:12345/apps.connections.open
> [DEBUG]  web-api:WebClient:0 http request body: {}
> [DEBUG]  web-api:WebClient:0 http request headers: {}
> [DEBUG]  web-api:WebClient:0 http response received
> [DEBUG]  web-api:WebClient:0 http request result: {"ok":true,"url":"ws://localhost:23456/","response_metadata":{}}
> [DEBUG]  web-api:WebClient:0 apiCall('apps.connections.open') end
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:authenticated
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:handshaking
> [DEBUG]  socket-mode:SocketModeClient:0 Received a message on the WebSocket: {"type":"hello"}
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connected
> [INFO]  socket-mode:SocketModeClient:0 Now connected to Slack
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connected:preparing
> [DEBUG]  socket-mode:SocketModeClient:0 Started running a new heart beat job
> terminating <ref *1> WebSocket { ... }
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connected:ready
>       ✔ should gracefully handle a peer disconnect
> [DEBUG]  socket-mode:SocketModeClient:0 Cancelled the job waiting for ping from Slack
> [DEBUG]  socket-mode:SocketModeClient:0 Terminated the heart beat job
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: reconnecting
> [INFO]  socket-mode:SocketModeClient:0 Reconnecting to Slack ...
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting
> [INFO]  socket-mode:SocketModeClient:0 Going to establish a new connection to Slack ...
> [DEBUG]  socket-mode:SocketModeClient:0 Transitioning to state: connecting:authenticating
> [DEBUG]  socket-mode:SocketModeClient:0 Going to retrieve a new WSS URL ...
> [DEBUG]  web-api:WebClient:0 apiCall('apps.connections.open') start
> [DEBUG]  web-api:WebClient:0 http request url: http://localhost:12345/apps.connections.open
> [DEBUG]  web-api:WebClient:0 http request body: {}
> [DEBUG]  web-api:WebClient:0 http request headers: {}
> 
> [WARN]  web-api:WebClient:0 http request failed connect ECONNREFUSED 127.0.0.1:12345
> 
>   1 passing (50ms)
> 
> [DEBUG]  web-api:WebClient:0 http request url: http://localhost:12345/apps.connections.open
> [DEBUG]  web-api:WebClient:0 http request body: {}
> [DEBUG]  web-api:WebClient:0 http request headers: {}
> [WARN]  web-api:WebClient:0 http request failed connect ECONNREFUSED 127.0.0.1:12345
> ```
> 
> No crashes, though with the websocket peer being offline, it should be expected that this client tries to reconnect forever unsuccessfully.
> 
> I will continue with releasing the latest `main` as v2 of socket-mode and close this issue.

We are getting this issue, I've tried upgrading to `7.0.2` but we still get this error randomly when we have traffic which is killing our service as it's an unhandled error.

We are running:
- node `v18.19.0`
- os `amazonlinux:2023.2.20231113.0`
- @slack/web-api `7.0.2`

The unhandled error bubbling up to main thread:
```
"code": "slack_webapi_platform_error",
"data": {
	"error": "account_inactive",
	"ok": false
}
```

Error stack:
```
Error: An API error occurred: account_inactive
    at platformErrorFromResult (/srv/node_modules/@slack/web-api/dist/errors.js:62:33)
    at WebClient.<anonymous> (/srv/node_modules/@slack/web-api/dist/WebClient.js:198:60)
    at Generator.next (<anonymous>)
    at fulfilled (/srv/node_modules/@slack/web-api/dist/WebClient.js:28:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
