### ISSUE TITLE
RTMClient websocket Unexpected server response: 408

### ISSUE THREAD

**Issue by Tjird** [slackapi/node-slack-sdk#632] opened 2018-09-12 07:42 UTC
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I have a bot that takes all messages being send in a specific channel. The connection to slack is not being closed, it should reconnect but doens't happends. 
`11-9-2018 09:30:39[ERROR] @slack/client:RTMClient2 A websocket error occurred: connect ETIMEDOUT [Amazon IP]
11-9-2018 09:47:11[ERROR] @slack/client:RTMClient2 A websocket error occurred: read ETIMEDOUT
11-9-2018 09:47:52[ERROR] @slack/client:RTMClient2 A websocket error occurred: Unexpected server response: 408`

The same bot but on a other Docker container he gave a other error, it is only taking from a other channel. Same bot token.

`11-9-2018 09:29:41[ERROR] @slack/client:RTMClient2 A websocket error occurred: connect ETIMEDOUT [Amazon IP]
11-9-2018 09:31:15[ERROR] @slack/client:RTMClient2 A websocket error occurred: socket hang up
11-9-2018 09:47:17[ERROR] @slack/client:RTMClient2 A websocket error occurred: read ETIMEDOUT`

I saw one closed issue about `408` but doesn't seems the same as my issue. If I have it wrong say it pls :P.

#### Reproducible in:

`@slack/client` version: 4.6.0

node version: 10.8.0

OS version(s): Linux Ubuntu 16.04

#### Steps to reproduce:

1. Make a bot that connect to slack with rtm.start
2. Take all messages that are being send in a channel
3. Let it run for a time

#### Expected result:

I expected that the bot reconnect after it disconnect.

#### Actual result:

It doens't reconnect after it disconnect.

#### Attachments:

`11-9-2018 09:30:39[ERROR] @slack/client:RTMClient2 A websocket error occurred: connect ETIMEDOUT [Amazon IP]
11-9-2018 09:47:11[ERROR] @slack/client:RTMClient2 A websocket error occurred: read ETIMEDOUT
11-9-2018 09:47:52[ERROR] @slack/client:RTMClient2 A websocket error occurred: Unexpected server response: 408`

`11-9-2018 09:29:41[ERROR] @slack/client:RTMClient2 A websocket error occurred: connect ETIMEDOUT [Amazon IP]
11-9-2018 09:31:15[ERROR] @slack/client:RTMClient2 A websocket error occurred: socket hang up
11-9-2018 09:47:17[ERROR] @slack/client:RTMClient2 A websocket error occurred: read ETIMEDOUT`

**Comment by Tjird** [comment] 2018-09-12 09:01
I recieve all messages with the type "message". https://i.imgur.com/1s8cr1J.png
The screenshot is the part that the RTMClient is being used, the other part of my code is not useful in this case.

**Comment by aoberoi** [comment] 2018-09-12 09:05
@Tjird thanks for providing the code. in addition to verifying my description above was correct, can you tell me if the issue ongoing for your bots or if it is intermittent? Has it stopped occurring?

**Comment by aoberoi** [comment] 2018-09-12 20:59
Okay, it seems like there might have been a brief network issue in your region or on the network between your host and our data center.

The `RTMClient` did retry the connection several times. It seems like it was functioning as expected. If you expect it to retry forever, you should change the default `retryPolicy` in the `RTMClient` constructor.

If the issue is resolved, do you think we can close this?

**Comment by Tjird** [comment] 2018-09-17 13:57
Yes you can close it, sorry for the late reaction @aoberoi

**Closed** 2018-09-17 17:47 UTC
Labels: needs feedback, question
