### ISSUE TITLE
Codecov reports should use fully qualified filenames

### ISSUE THREAD

**Issue by aoberoi** [slackapi/node-slack-sdk#852] opened 2019-08-20 20:16 UTC
### Description

Currently when Codecov collects/aggregates coverage reports for a specific change, the reports from several packages collide in a way that makes the aggregations incorrect. For example, both the `@slack/web-api` and `@slack/webhoook` packages include a file called `src/errors.ts`. For Codecov, these are the same file.

There is a separate, but potentially related problem that sometimes the commit SHA that Travis prints out after the coverage report upload does not match the commit SHA from the branch (pull request). When this happens, the PR on GitHub will never receive a status check result. Upon re-running the build, it sometimes will match, and then Codecov's status check will be present.

Related: #851 

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment] 2021-03-22 09:54
This issue seems to be still relevant. https://codecov.io/gh/slackapi/node-slack-sdk/tree/main/src

**Comment by filmaj** [comment] 2024-01-26 21:03
Closing as duplicate of #838

**Closed by filmaj** 2024-01-26 21:03 UTC
Labels: good first issue, tests, auto-triage-skip
