### ISSUE TITLE
Incorrect typescript definitions

### ISSUE THREAD

**Issue by malmaud** [slackapi/node-slack-sdk#581] opened 2018-06-12 14:11 UTC
### Description

Unless I'm missing something, the typescript definitions of the return values of the Web API methods are missing fields. They all seem to return `WebAPICallResult`, which doesn't have any of the properties specific to the method. For example, WebClient().channels.list() has no property `channels`.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.3.1

node version: 10.4.0

OS version(s): OS X 10.13.5

#### Steps to reproduce:

```typescript
import {WebClient} from '@slack/client'

async function test() {
  const client =  new WebClient('blah')
  const result = await client.channels.list()
  let channels = result.channels
}
```

#### Expected result:

TypeScript compiles this file without warning

#### Actual result:

TypeScript  compiler outputs `Property 'channels' does not exist on type 'WebAPICallResult'.`

**Comment by aoberoi** [comment] 2018-06-12 15:25
You’re not missing anything, this is a known issue. `WebAPICallResult` wasn’t designed to be a “closed” interface, just a minimal common interface for results of all different method calls. We hope to do better soon. 

This is a duplicate of #509, so I’ll close this to consolidate. There’s been some progress in #563, and some relevant discussion in #496.

**Closed by aoberoi** 2018-06-12 15:25 UTC

**Comment by malmaud** [comment] 2018-06-12 15:58
Ah, thank you. Sorry for missing those closed issues.
