### ISSUE TITLE
Update documentation to remove Workspace apps

### ISSUE THREAD

**Issue by shanedewael** [slackapi/node-slack-sdk#670] opened 2018-12-13 18:50 UTC
### Description

Following the deprecation of workspace apps (read more in [the blog post](https://medium.com/slack-developer-blog/an-update-on-workspace-apps-aabc9e42a98b)), we should remove mention of workspace apps in the documentation.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by aoberoi** [comment] 2018-12-14 06:40
i think this is a duplicate of #668

**Closed** 2018-12-14 06:40 UTC
Labels: duplicate
