### ISSUE TITLE
presence_change event detection stops after a few hours

### ISSUE THREAD

**Issue by nikhila-3012** [slackapi/node-slack-sdk#1224] opened 2021-05-04 09:54 UTC
### I am using @slack/rtm-api to monitor status change of users on slack. 

The code is designed to wait till there is a status change and report it. It works fine for fews hours after which it stops identifying the change.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: "^5.0.5"

node version:10.23.0

OS version(s): Mac OS Big Sur

#### Steps to reproduce:

1. 
2.
3.

#### Expected result:

It should report change in status like so :
```
2021-05-01T20:18:34.93+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 sending message on websocket: {"type":"ping","id":39}
   2021-05-01T20:18:34.93+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 setting pong timer
   2021-05-01T20:18:34.93+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"pong","reply_to":39}
   2021-05-01T20:18:34.93+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 received pong, clearing pong timer
   2021-05-01T20:18:37.15+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"presence_change","presence":"away","user":"WQ0AV59UG"}
   2021-05-01T20:18:37.16+0530 [APP/PROC/WEB/0] OUT { t**ype: 'presence_change', presence: 'away', user: 'WQ0AV59UG**' }
   2021-05-01T20:18:37.16+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 send() in state: connected,ready
   2021-05-01T20:18:37.16+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 setting ping timer
   2021-05-01T20:18:37.16+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 sending message on websocket: {"text":"User:Pre Prod 1 Presence:away ","channel":"C01G74L6ZD4","type":"message","id":40}
```

#### Actual result:

As seen below logs the change is not detected

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.
```
2021-05-03T16:04:37.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 ping timer expired, sending ping
   2021-05-03T16:04:37.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 send() in state: connected,ready
   2021-05-03T16:04:37.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 setting ping timer
   2021-05-03T16:04:37.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 sending message on websocket: {"type":"ping","id":11980}
   2021-05-03T16:04:37.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 setting pong timer
   2021-05-03T16:04:37.97+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"pong","reply_to":11980}
   2021-05-03T16:04:37.97+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 received pong, clearing pong timer
   2021-05-03T16:04:41.72+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"file_deleted","file_id":"F021DQJCVJL","channel_ids":[],"event_ts":"1620038081.188300"}
   2021-05-03T16:04:42.02+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"file_deleted","file_id":"F02097PU015","channel_ids":[],"event_ts":"1620038081.188600"}
   2021-05-03T16:04:43.24+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"file_deleted","file_id":"F021DQMDFUG","channel_ids":[],"event_ts":"1620038083.188900"}
   2021-05-03T16:04:43.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:KeepAlive:0 ping timer expired, sending ping
   2021-05-03T16:04:43.89+0530 [APP/PROC/WEB/0] OUT [DEBUG]  rtm-api:RTMClient:1 send() in state: connected,ready
```

**Comment by misscoded** [comment] 2021-05-04 22:38
Hi @nikhila-3012! After doing a little digging, the issue you've opened appears very similar to [this one](https://github.com/slackapi/node-slack-sdk/issues/515). Could you review [the suggestion made](https://github.com/slackapi/node-slack-sdk/issues/515#issuecomment-375090091) there and let us know if that also resolves this issue?

**Comment by nikhila-3012** [comment] 2021-05-05 06:27
@misscoded Thanks for the response. I am trying the work around will let you know after 2 days.

**Comment by nikhila-3012** [comment] 2021-05-06 07:00
@misscoded Subscribing when the state changes to ready didnt help. I am still facing the same issue

**Comment by misscoded** [comment] 2021-05-18 04:36
Hmm. Could you provide some code, similar to as was done in the issue linked above, so that we can get a better understanding and potentially reproduce it?

**Comment by nikhila-3012** [comment] 2021-05-19 09:41
Below is a piece of the code , do let me know if you need more info
```
rtm.on('ready',() => {
rtm.subscribePresence(trackedUserIds); 

  rtm.on('presence_change', (event) => {
  //meant to send a message to slack channel reporting the change 
        
          
         }
    });
rtm.on('disconnected',(event)=>{
    console.log("slack connection disconnected",event);
    rtm.sendMessage("Disconnected");
});
rtm.on('reconnecting',(event)=>{
    console.log("slack connection reconnecting",event);
    rtm.sendMessage("Reconnecting");
});
rtm.on('connected',(event)=>{
    console.log("slack connection established",event);
    rtm.sendMessage("Connected");
});
    
    });

  
(async () => {
  // Use the batch_presence_aware start option
 const result = await rtm.start({ batch_presence_aware: true })
  .catch(console.error);
})();

```

**Comment by CodeBradley** [comment] 2021-05-22 23:19
@nikhila-3012 Sorry I don't have an answer for you, but I can't even get rtm.start() to work because it doesn't work with new apps and I can't get it to work with old apps either. How did you create an app to work with RTM at all? I'm trying to work on something similar.

<img width="740" alt="Screen Shot 2021-05-22 at 5 30 37 PM" src="https://user-images.githubusercontent.com/3913066/119243206-4b395080-bb2a-11eb-99d0-935493282b92.png">

**Comment by seratch** [comment] 2021-05-24 00:47
Hi @nikhila-3012 , I've answered a similar question at https://github.com/slackapi/node-slack-sdk/issues/1245#issuecomment-846660027 I hope it was helpful for you too.

**Comment by nikhila-3012** [comment] 2021-05-24 05:44
@CodeBradley Yes you need to create a classic app for the events api to work.

**Comment by seratch** [comment] 2021-06-03 04:16
I think we've provided an answer to this question. Let me close this issue now but please feel free to write in if you have anything further.

**Comment by nikhila-3012** [comment] 2021-06-03 05:07
@seratch The issue is not fixed it still persists

**Comment by seratch** [comment] 2021-06-03 05:13
@nikhila-3012 Can you try the steps I shared at https://github.com/slackapi/node-slack-sdk/issues/1245#issuecomment-846660027 ?

**Comment by nikhila-3012** [comment] 2021-06-03 05:17
@seratch Took a look it .. its not related to the issue. The issue is The code is designed to wait till there is a status change and report it. It works fine for fews hours after which it stops identifying the change. and the work around https://github.com/slackapi/node-slack-sdk/issues/1224#issuecomment-832293765 didnt work

**Comment by seratch** [comment] 2021-06-03 05:26
Thanks and sorry for overlooking the description. I will reopen this and change the title a bit. I will check this later.

**Comment by seratch** [comment] 2021-06-03 06:32
@nikhila-3012 If the issue you're facing is related to reconnection, I've confirmed that the following code works after reconnecting. If the issue is not related to reconnection and it can occur after a few hours pass, I need to see how it goes.

```js
const { RTMClient } = require('@slack/rtm-api');
const { WebClient } = require('@slack/web-api');

// Read a token from the environment variables
const token = process.env.SLACK_BOT_TOKEN;

const client = new WebClient(token, { logLevel: 'debug' });
const rtm = new RTMClient(token, { logLevel: 'debug' });

const trackedUserIds = [];

rtm.on('ready', async () => {
  await rtm.subscribePresence(trackedUserIds);
});
rtm.on('presence_change', async (event) => {
  console.log(`User: ${event.user} Presence: ${event.presence}`);
});

(async () => {
  trackedUserIds.push(...(await client.users.list({ limit: 10 })).members.map((m) => m.id));
  await rtm.start();
})();
```

**Comment by seratch** [comment] 2021-06-04 02:13
@nikhila-3012 I have been running the above script on my local machine for more than 20 hours and I haven't observed any issues with it. The app always prints the following logs right after I manually change the presence of a user.

```
[DEBUG]  rtm-api:RTMClient:1 received message on websocket: {"type":"presence_change","presence":"away","user":"U11111"}
User: U11111 Presence: away
```

According to the app logs, the app had reconnection multiple times and every time, the `ready` handler is called and subscriptions are successfully enabled.

If possible, may I ask you to try the same script on your end? By doing so, you may be able to narrow the issue down.

>trackedUserIds.push(...(await client.users.list({ limit: 10 })).members.map((m) => m.id));

The part initializing `trackedUserIds` can be adjusted for your use case. You can pass a static array instead.

If the above script works with a brand new app and you see the issue you mentioned here only with a specific workspace or app, I recommend contacting the Slack customer support agents. They can check more details with shared workspace, app information.

I hope this was helpful to you.

**Comment by seratch** [comment] 2021-06-19 00:48
@nikhila-3012 Let us know if you have further to ask here. We'll close this issue after waiting for your response for a few weeks.

**Comment by nikhila-3012** [comment] 2021-06-19 14:47
@seratch No I dont have more questions. Thank you

**Closed** 2021-06-20 12:32 UTC
Labels: pkg:rtm-api, question
