### ISSUE TITLE
Websocket Error (Unexpected server response: 408)

### ISSUE THREAD

**Issue by hankjacobs** [slackapi/node-slack-sdk#1472] opened 2022-04-20 17:14 UTC
#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] `@slack/oauth`
- [X] `@slack/socket-mode`
- [ ] I don't know

#### The Slack SDK version

3.11.0

#### Node.js runtime version

v17.9.0

#### OS info

Ubuntu 18.04.6 LTS

#### Steps to reproduce:

1. run socket mode app for extended period of time

### Expected result:

an error is not thrown

### Actual result:

The following "Unexpected server response" is thrown (sorry, no stack trace on this one):

```
A websocket error occurred: Unexpected server response: 408
  ```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by seratch** [comment] 2022-04-20 21:44
Hi @hankjacobs, thanks for sharing this. Can I ask you to share a bit more details?

* What was the outcome in the scenario? App process crash? No other side affect?
* Did your app manage to reconnect to Slack (without restarting the app)?

I am not sure what the root cause of the 408 HTTP status for the WebSocket connection in this scenario but probably it was caused by either a Slack server incident/outage or some network connection issues between the Slack server and your app. We've never received this inquiry in the past and this indicates this is not a common error situation. Either way, the next minor version v1.3.0 would be more robust for error patterns. 

The error may still happen again in the future. However, as long as your app continues working even in the scenario, we would like to close this issue now. As the maintainers of `@slack/socket-mode` library, we are unable to eliminate the HTTP status errors that happen in the communications managed by `ws` package.

I hope this was clear enough to you.

**Closed** 2022-04-26 18:02 UTC
Labels: needs info, pkg:socket-mode
