### ISSUE TITLE
v4.0.0 - IncomingWebhook errors with a TypeError

### ISSUE THREAD

**Issue by dustingraves** [slackapi/node-slack-sdk#492] opened 2018-03-12 22:38 UTC
### Description

`IncomingWebhook` errors with a `TypeError: util_1.callbackify is not a function`

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.0.0

node version: 6.10.0

OS version(s): OS X 10.13.1

#### Steps to reproduce:

2. Initiate a new webhook process
3. try to send a message via webhook

#### Expected result:

It should work

#### Actual result:

Throws a TypeError

#### Attachments:

```shell
TypeError: util_1.callbackify is not a function
    at IncomingWebhook.send (project/node_modules/@slack/client/dist/IncomingWebhook.js:38:16)
    at slackWebhookResponse (project/src/lib/utils.js:84:13)
    at wrapper (project/node_modules/lodash/lodash.js:5205:19)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

**Comment by aoberoi** [comment] 2018-03-12 22:46
thanks for reporting! this was a tricky bug, but its actually already been fixed via #480. the underlying cause was a silly typo (`util` instead of `./util`).

**Closed** 2018-03-12 22:47 UTC
Labels: bug

**Comment by johnnymn** [comment] 2018-03-12 23:04
+1 Confirmed this is happening on Amazon Linux too!

**Comment by glajchs** [comment] 2018-03-13 17:15
I stupidly put a stack-overflow question for this here [https://stackoverflow.com/questions/49261409/node-slack-sdk-tutorial-wont-run-with-typeerror-cannot-set-property-text-of](https://stackoverflow.com/questions/49261409/node-slack-sdk-tutorial-wont-run-with-typeerror-cannot-set-property-text-of).  Anyways, in trying to grab the latest master version, I can't get it to run (require complains that it can't find "@slack/client").  Am I doing this wrong in my package.json `"@slack/client": "git://github.com/slackapi/node-slack-sdk.git#master"`?  If I change the version back to "3.16.0", it works fine.

**Comment by aoberoi** [comment] 2018-03-13 17:40
@glajchs: thanks for being willing to run on the bleeding edge and giving us constructive feedback. This is very valuable to the community. 

That’s not going to work because the repo doesn’t contain the final built JS. Instead, you could clone the repo to another local folder, `npm install` to download the dependencies, and the `npm run build` to convert the TypeScript to JavaScript.
