### ISSUE TITLE
Why is `WebAPICallOptions` not type-safe?

### ISSUE THREAD

**Issue by rr-codes** [slackapi/node-slack-sdk#1231] opened 2021-05-10 16:58 UTC
### Description

I recently encountered a bug that was due to using a non-existent property in `ChatPostMessageArguments`, which I assumed would not have been possible as it is a TypeScript interface. But such interface extends `WebAPICallOptions`, which allows any arbitrary key value pair, effectively removing its static type checking.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by mwbrooks** [comment] 2021-05-11 04:56
Hi @rr-codes, this is a good question! My understanding is that the [arbitrary keys were added for pagination support](https://github.com/slackapi/node-slack-sdk/commit/f1f7d4d72f0566b205c72df70b50ef608d442f43). Ideally, we would change it, but we must find a way to safely remove it from pagination. If we did, it would be a breaking change and need to be released in our next major version bump.

@kaz Since you're focused heavily on TS support right now, do you want to discuss this change more and possibly turn this into a task for the next major?

**Comment by filmaj** [comment] 2023-10-04 16:01
Closing this as a duplicate of #1323

**Closed by filmaj** 2023-10-04 16:01 UTC
Labels: semver:major, discussion, area:typescript, pkg:web-api
