### ISSUE TITLE
Bug: installer callback fails when one path param differ from slack redirect url

### ISSUE THREAD

**Issue by SweetSheldon** [slackapi/node-slack-sdk#1281] opened 2021-07-06 17:39 UTC
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x ] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [ x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [ x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [ x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Installer.handeCallback fails when one path param differ from slack redirect url. For example i have 
https://2a2efa2f1308.ngrok.io/admin/api/slack/connect redirect url in slack app settings, but pass to installer 
https://2a2efa2f1308.ngrok.io/admin/api/slack/connect/test, so i got bad_redirect_error.
I generate url with installer.generateInstallUrl

<img width="1602" alt="Снимок экрана 2021-07-06 в 19 25 39" src="https://user-images.githubusercontent.com/48868754/124643728-15fa7f00-de9a-11eb-953f-9e550e4de358.png">

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ x ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: 2.1.0

node version: 14.16.0

OS version(s): macOS Big Sur 11.2.3

#### Steps to reproduce:

1. Pass to slack oauth url
2. Add /anything
3. Check it

#### Expected result:

What you expected to happen

#### Actual result:

What actually happened

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by mwbrooks** [comment] 2021-07-06 18:28
Hey @SweetSheldon, thanks for reaching out!

Could you provide a code sample to reproduce setting up your Slack OAuth URL. I may be able to help you more when I see the code because right now this sounds like the expected behaviour.

Cheers!
Michael

**Comment by SweetSheldon** [comment] 2021-07-06 19:16
Here is code samples. I generate url, then handle code after OAuth with installer.handleCallback. So when i have in Slack App settings url like https://someurl.ngrok.io/admin/api/slack/connect/ and pass redirect url to installer.generateInstallUrl https://someurl.ngrok.io/admin/api/slack/connect/test. I become such issue.
<img width="702" alt="Снимок экрана 2021-07-06 в 22 15 31" src="https://user-images.githubusercontent.com/48868754/124654873-c7ec7800-dea7-11eb-8541-51e5b1b117eb.png">
<img width="588" alt="Снимок экрана 2021-07-06 в 22 10 10" src="https://user-images.githubusercontent.com/48868754/124654592-675d3b00-dea7-11eb-872d-e4554c366434.png">
<img width="683" alt="Снимок экрана 2021-07-06 в 22 10 26" src="https://user-images.githubusercontent.com/48868754/124654494-4a286c80-dea7-11eb-846f-1472dbb24cf1.png">

**Comment by joshuavoydik** [comment] 2021-07-06 19:20
@mwbrooks thanks for the help. I'm working with @SweetSheldon on the Slack integration.

**Comment by mwbrooks** [comment] 2021-07-11 05:42
Hey @SweetSheldon,

Sorry about the slow response. The week got away from me and I didn't notice you quick response on this issue.

Thanks a lot for all of the details 🙂 My first suggestion is to try updating your **Redirect URLs** on api.slack.com:
* From: https://your-domain.ngrok.io/admin/api/slack/connect/test
* To: https://your-domain.ngrok.io/admin/api/slack/connect

The reason is that the URL provided must [partially match the Redirect URL](https://api.slack.com/legacy/oauth#authenticating-users-with-oauth__redirect-uris).

I'll keep an better 👀 on this issue, so let me know how that goes!

**Comment by seratch** [comment] 2021-09-24 08:57
Hi @SweetSheldon, was @mwbrooks's comment helpful? Please let us know if you need more help here 👋 We'll close this issue if we don't hear back for a few days.

**Comment by seratch** [comment] 2021-10-07 23:01
👋 Let us close this issue now but please feel free to write in whenever you have more to ask here!

**Closed by seratch** 2021-10-07 23:01 UTC
Labels: question
