### ISSUE TITLE
WebSocket error occurred: Unexpected server response: 409

### ISSUE THREAD

**Issue by gdhardy1** [slackapi/node-slack-sdk#2094] opened 2024-11-03 14:46 UTC
Socket mode receiver fails to make a successful connection due to `WebSocket error occurred: Unexpected server response: 409` error. Retries after this error occurs may eventually lead to a successful connection or worse, rate limiting from Slack servers on the `apps.connections.open` call.

### `@slack/bolt` version

4.0.1

### Your `App` and Receiver Configuration

Socket mode 2.0.2

### Node.js runtime version

v20.17.0

### Steps to reproduce:

This error seems to reproduce only when launching in a distributed environment (i.e. launching 2 or more instances of the app).
Nothing special is being done on start up. It is minimally reproducible using the example from [BoltJS Getting Started](https://tools.slack.dev/bolt-js/getting-started/) docs as a basis.

```javascript
const app = new App({
  socketMode: true,
  token: process.env.BOT_TOKEN,
  signingSecret: process.env.SIGNING_SECRET,
  appToken: process.env.APP_TOKEN,
  logger
});

void (async () => {
  // Start your app
  await app.start(Number(process.env.PORT) || 3000);

  console.log('⚡️ Bolt app is running!');
})();
```
1. Open multiple shell terminals (suggested 5) and change `process.env.PORT` to a different number in each shell
2. Quickly start the bolt app in each shell (roughly simultaneously to mimic deployment as a server group)

### Expected result:

Each instance of the app should start up successfully without the `WebSocket error occurred: Unexpected server response: 409` error

### Actual result:
First we see the Socket Mode client successfully initialized.
```
[14:05:55.636] DEBUG (36123): Initializing SocketModeReceiver
[14:05:55.636] DEBUG (36123): The logLevel given to Socket Mode was ignored as you also gave logger
[14:05:55.637] DEBUG (36123): The logLevel given to WebClient was ignored as you also gave logger
[14:05:55.637] DEBUG (36123): initialized
[14:05:55.637] DEBUG (36123): The Socket Mode client has successfully initialized
[14:05:55.637] DEBUG (36123): apiCall('auth.test') start
[14:05:55.638] DEBUG (36123): http request url: https://slack.com/api/auth.test
[14:05:55.638] DEBUG (36123): http request body: {"token":"[[REDACTED]]"}
[14:05:55.638] DEBUG (36123): http request headers: {"Accept":"application/json, text/plain, */*","User-Agent":"@slack:socket-mode/2.0.2 @slack:bolt/4.0.1 @slack:web-api/7.7.0 node/20.17.0 linux/6.8.0-1017-aws","Authorization":"[[REDACTED]]"}
```

Then we see the `409` error and the following logs repeat over and over again until:
- the connection is established OR 
- the app is rate limited
```
[14:05:55.639] DEBUG (36123): Starting Socket Mode session ...
[14:05:55.639] DEBUG (36123): Going to retrieve a new WSS URL ...
[14:05:55.639] DEBUG (36123): apiCall('apps.connections.open') start
[14:05:55.639] DEBUG (36123): http request url: https://slack.com/api/apps.connections.open
[14:06:46.734] DEBUG (36239): http request body: {}
[14:06:46.734] DEBUG (36239): http request headers: {"Accept":"application/json, text/plain, */*","User-Agent":"@slack:socket-mode/2.0.2 @slack:bolt/4.0.1 @slack:web-api/7.7.0 node/20.17.0 linux/6.8.0-1017-aws","Authorization":"[[REDACTED]]"}
[14:06:46.755] DEBUG (36239): http response received
[14:06:46.755] DEBUG (36239): http request result: {"ok":true,"url":"wss://wss-primary.slack.com/link/?ticket=084fad38-f4fe-4fba-9057-fedc6792738f&app_id=4cd5f1068f00f78fe83741337c42c958d96b3b3b13a7e17b4cda776e289e362c","response_metadata":{"scopes":["connections:write"],"acceptedScopes":["connections:write"]}}
[14:06:46.755] DEBUG (36239): apiCall('apps.connections.open') end
[14:06:46.755] DEBUG (36239): Initiating new WebSocket connection.
[14:06:46.768] ERROR (36239): WebSocket error occurred: Unexpected server response: 409
[14:06:46.768] DEBUG (36239): WebSocket already disconnected, flushing remainder.
[14:06:46.768] DEBUG (36239): Before trying to reconnect, this client will wait for 5000 milliseconds
[14:06:46.768] ERROR (36239): WebSocket error! Error: Failed to send message on websocket: Unexpected server response: 409
[14:06:46.768] DEBUG (36239): WebSocket close frame received (code: 1006, reason: )
[14:06:46.768] DEBUG (36239): WebSocket already disconnected, flushing remainder.
[14:06:46.768] DEBUG (36239): Before trying to reconnect, this client will wait for 10000 milliseconds
[14:06:46.779] DEBUG (36239): Continuing with reconnect...
```

### Additional Notes
It seems that a successfully established connection does not mean the app is in a "safe" state. While running, I've observed both `Primary WebSocket error occurred: Unexpected server response: 409` and `Secondary WebSocket error occurred: Unexpected server response: 409` errors as well. The behavior is basically identical to as described above.

**I've also observed this on `@slack/bolt-js` versions as early as `3.20.0`.**

**Comment by filmaj** [comment] 2024-11-06 19:07
Thanks for the analysis. I've moved this issue over to the node-slack-sdk (the home of the `socket-mode` client); will sift through everything you've posted and see if I can capture the issue as a test to help frame the discussion.

Separate issue: I think I will riff on your repro a bit to add `Retry-After` header responses to the `apps.connections.open` endpoint to see if retry handling works as expected. Will see what kind of responses that API raises in a rate limit scenario.

**Comment by bitofsky** [comment] 2024-11-10 04:03
![image](https://github.com/user-attachments/assets/9236eebb-107a-49e9-8231-59c5a855ba11)

Hello, I recently encountered the same issue.

When running two instances of a Bolt app, one of the apps would unexpectedly disconnect from the socket connection. During the reconnection process, it would fail repeatedly, doubling the reconnection attempts each time. This cycle continued until it led to an Out of Memory (OOM) error, eventually causing the app to crash.

```
[ERROR]  socket-mode:SocketModeClient:0 WebSocket error! Error: Failed to send message on websocket: Unexpected server response: 409
[ERROR]  socket-mode:SlackWebSocket:1843 WebSocket error occurred: Unexpected server response: 409
[WARN]  bolt-app http request failed A rate limit was exceeded (url: apps.connections.open, retry-after: 2)
```

**Comment by filmaj** [comment] 2024-11-12 15:28
Update here: I have escalated this issue to the real-time server backend team to raise the issue related to unexpected 409 responses from that server.

I am still working on addressing the issue of what this socket-mode library should do in this situation and how to prevent it from getting into a rate-limit situation with the `apps.connections.open` API.

**Comment by bitofsky** [comment] 2024-11-12 23:06
@matthewhenry1 Thanks for the response. I was running on @slack/bolt `4.0.1`. I'll upgrade to `4.1.0` and test if the issue persists.

**Comment by filmaj** [comment] 2024-11-13 16:24
The underlying issue still exists in bolt 4.x, the only thing upgrading to 4.x may help is if you experience crashes with a class of errors in the form "unhandled event X in state Y", e.g. "Unhandled event 'server explicit disconnect' in state 'connecting'." (as described in [this comment](https://github.com/slackapi/node-slack-sdk/issues/1771#issuecomment-2122595584)).

**Comment by alisd23** [comment] 2024-11-15 11:02
Just to add some more info: I'm also experiencing this issue in a distributed setup, and I'm also sharing app tokens across environments (local, staging, live) which is maybe a bad idea. I'm consistently getting 409 errors. Looking at the logs it seemingly starts with a random `409` response, then ends up in an out of control (seemingly exponential) chain reaction of reconnections - as others have seen. I might have to remove the integration as it's spamming our logs (and CPU resource) so much.

<img width="1167" alt="image" src="https://github.com/user-attachments/assets/103b9dee-7ac8-475a-8106-e19093c0a8f7">

Given it's probably a distributed problem - could it be some connection limit issue? The original example of this issue uses *5* instances, which is less than the max *10* connection limit shown here: https://api.slack.com/apis/socket-mode#connections. Could this limit be the cause of the `409` errors, and could this limit be wrong in the docs - i.e. lower than it mentions? I'm fairly sure I don't have 10 instances in total at any time though.

Related question: Does anyone know if this limit is *per app token* or per *app*?

I'm using latest version `4.1.0`.

**Comment by bitofsky** [comment] 2024-11-16 11:03
> @matthewhenry1 Thanks for the response. I was running on @slack/bolt `4.0.1`. I'll upgrade to `4.1.0` and test if the issue persists.

I have confirmed that the same issue persists in version 4.1.0.

**Comment by filmaj** [comment] 2024-11-18 14:20
This does seem to be an infrastructural issue; from what I understand, the 409 response should be an internal-only signal for the real-time backend system to find another container to serve the connection request. For whatever reason (a recent change or bug), it is bubbling up to the public / to the apps. The infrastructure team is still investigating the cause.

**Comment by dschneck-ibm** [comment] 2024-11-21 23:18
IBM is hitting this issue attempting to upgrade a major Slack application.  Our only workaround was to decrease the number of instances of the application to 1. That is an unacceptable workaround. The reason we are upgrading is because of this issue [Unhandled event 'server explicit disconnect ](https://github.com/slackapi/node-slack-sdk/issues/1771) causing frequent, unexpected restarts of all the app instances. How can we proceed if web socket 1.x is a problem and web socket 2.x is a problem?  We need fixes or workarounds.

**Comment by yichennnn36** [comment] 2024-11-22 03:48
I also encountered the same issue. Because I have two instances of a Bolt app.
How could I resolve this problem? or how could I detect error and disconnected the Bolt app
```
[ERROR]  socket-mode:SocketModeClient:0 WebSocket error! Error: Failed to send message on websocket: Unexpected server response: 409
[ERROR]  socket-mode:SlackWebSocket:1843 WebSocket error occurred: Unexpected server response: 409
[WARN]  bolt-app http request failed A rate limit was exceeded (url: apps.connections.open, retry-after: 2)
```

**Comment by filmaj** [comment] 2024-11-22 16:28
I have a draft PR that at least depicts the issue in an integration test in this repo: https://github.com/slackapi/node-slack-sdk/pull/2099

**Comment by filmaj** [comment] 2024-11-25 14:04
Another update: on Friday afternoon EST, a backend configuration problem was identified and we started partially rolling out a fix. Since then, we have seen metrics indicating that 409 errors are properly being consumed internally which should prevent them from being raised to applications. This fix will be rolled out fully today (Monday) and tomorrow, as so far it is only being partially rolled out to monitor impact on applications.

We expect the occurrence of 409s should have reduced since Friday and for them to be gone by Tuesday.

**Comment by gdhardy1** [comment] 2024-11-26 00:26
Thanks. Confirming that while yesterday I saw ~45,000, today I only two early in the AM.

**Comment by filmaj** [comment] 2024-11-26 16:34
Update: the backend fix has been rolled out to 75% and we expect to crank it up to 100% if not today then this week.

Also: as I mentioned, a PR is up with a proposed fix here: https://github.com/slackapi/node-slack-sdk/pull/2099

This fix is available as a pre-release as `@slack/socket-mode@2.0.3-rc.1` under the npm dist tag `2.0.3rc` (see `socket-mode` versions here: https://www.npmjs.com/package/@slack/socket-mode?activeTab=versions). Additionally, I have pre-released this pre-release in a bolt-js pre-release (yo dawg) as `@slack/bolt@4.1.2-rc.1` under the npm dist tag `4.1.2rc` (see `bolt` versions here: https://www.npmjs.com/package/@slack/bolt?activeTab=versions). For bolt-js devs affected by this bug, we would love if you could take either of these pre-releases for a spin and let us know how it works for you.

**Closed** 2024-12-09 19:36 UTC
Labels: bug, needs info, pkg:socket-mode, backend

**Comment by zimeg** [comment] 2024-12-09 19:55
@gdhardy1 Thanks so much for this detailed report 🙏 📚

The backend fix for this has finished rolling out and #2099 was merged for the next [`@slack/socket-mode@2.0.3`](https://github.com/slackapi/node-slack-sdk/milestone/129) release! 

We're hoping with both of these changes that fewer unexpected errors and erroring reconnections happen, but please feel free to write back in if unexpected logs appear again 🔍

**Comment by gdhardy1** [comment] 2024-12-10 19:39
No problem! I appreciate everyone's diligence fixing this issue and I'm glad this landed.

**Comment by zimeg** [comment] 2024-12-17 02:14
@gdhardy1 Thanks again for helping us test these changes! The latest [`@slack/bolt@4.2.0`](https://github.com/slackapi/bolt-js/releases/tag/%40slack%2Fbolt%404.2.0) release has the changes found in `@slack/socket-mode@2.0.3` included 🎁 ✨
