### ISSUE TITLE
Installation flow is not working for app without token rotation

### ISSUE THREAD

**Issue by flashua** [slackapi/node-slack-sdk#1346] opened 2021-09-24 11:44 UTC
### Description

Describe your issue here.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x ] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x ] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x ] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

By using InstallProvider for bot app without token rotation, it fails with 
`{'ok': False, 'error': 'invalid_auth'}` during authentication flow. It's happening due to call for `app.client.
auth.test` with user token (xoxp-***). The same call with bot token (xoxb-***) is working fine. 

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x ] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [ ] I don't know

#### Reproducible in:

package version: ^2.3.0

node version: v14.17.6

OS version(s): Win10

#### Steps to reproduce:
short one:
1. get some user token
2. call POST https://slack.com/api/auth.test with user token payload `{token: 'xoxp-*****'}`
3. observe error

complete one:

1. Setup some bot app without tokens rotation
2. setup oauth flow using this doc https://slack.dev/bolt-js/concepts#authenticating-oauth
3. run the installation flow via a generated link from `generateInstallUrl()` method
4. observe an error in the end

#### Expected result:

Either `https://slack.com/api/auth.test ` or installation flow (shipped from this module) is working fine 

#### Actual result:

The flow has been terminated with `{'ok': false, 'error': 'invalid_auth'}`

**Comment by seratch** [comment] 2021-09-24 22:37
Hi @flashua, thanks for writing in! 

OAuth apps without token rotation do work for me without any issues. To help us understand the issue that you're facing, could you share a minimum working example code that reproduces your situation?

**Comment by flashua** [comment] 2021-10-02 22:11
@seratch Before sending the testing app here I have tested, described scenarios, with different user permission scopes. I have found that https://api.slack.com/methods/auth.test/test API works only when user token relates to `users.profile:read` or similar permission. Before, we have an only identity.basic permission, which seems not enough to work properly. With adding users.profile:read permission everything works fine

The issue can be closed

P.S. For others who has faced a similar issue, please play with different permission scopes to resole the problem

**Comment by seratch** [comment] 2021-10-04 00:26
@flashua Thanks for your reply. Yes, `identity.basic`, `openid` are a bit different from other scopes. 

Glad to hear that you've figured out the cause! Let us close this issue now.

**Closed by seratch** 2021-10-04 00:26 UTC
Labels: question, needs info
