### ISSUE TITLE
StateMachine: unhandled event 'websocket close' in state 'connecting'

### ISSUE THREAD

**Issue by malonecm** [slackapi/node-slack-sdk#531] opened 2018-04-12 18:55 UTC
### Description

Have an always running bot. Had a random crash on 4.1.0 today. Trace follows, which hopefully will help. Not really reproducible. Hopefully just a state transition missing in your state machine.

/opt/local/slack-bot/node_modules/finity/lib/core/StateMachine.js:76
```
throw new Error('Unhandled event \'' + event + '\' in state \'' + this.currentState + '\'.');
^
Error: Unhandled event 'websocket close' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/opt/local/slack-bot/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /opt/local/slack-bot/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/opt/local/slack-bot/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/opt/local/slack-bot/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/opt/local/slack-bot/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at WebSocket.websocket.addEventListener.event (/opt/local/slack-bot/node_modules/@slack/client/dist/RTMClient.js:375:77)
    at WebSocket.onClose (/opt/local/slack-bot/node_modules/ws/lib/event-target.js:124:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at _receiver.cleanup (/opt/local/slack-bot/node_modules/ws/lib/websocket.js:220:12)
    at Receiver.cleanup (/opt/local/slack-bot/node_modules/ws/lib/receiver.js:557:13)
    at WebSocket.finalize (/opt/local/slack-bot/node_modules/ws/lib/websocket.js:206:20)
    at emitNone (events.js:111:20)
    at TLSSocket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.1.0

node version: v8.10.0

OS version(s): Amazon Linux (4.9.76-38.79.amzn2.x86_64)

#### Steps to reproduce:

1. Single occurrence while running an always-on bot, possibly related to network changes

#### Expected result:

From the error, it sounds like the websocket should just attempt to restart itself if it gets a close while it is connecting.

#### Actual result:

Node crashed and systemd restarted it, resulting in very small downtime

#### Attachments:

None

**Comment by aoberoi** [comment] 2018-04-13 00:51
thanks for reporting @malonecm 

this sounds like its potentially related to #527, since they both have to do with the websocket being in a closing state unexpectedly. we're a little low on data around how this would happen, but that stack trace is definitely useful, thanks for that.

are you able to increase the `logLevel` in the `RTMClient` instance and share those logs in case you see this happen again? i think it would be nice to compare to #527 and also help me trace the steps in order to reproduce.

**Comment by aoberoi** [comment] 2018-04-18 23:03
@malonecm looks like you found another issue to me. the new one seems a little more insidious, too.

for this second one, it would be useful to see the log statements from the `KeepAlive` class. did you filter those out or turn them off specifically? if you're able to get in there and tweak things, mind turning them on too for the next occurrence?

**Comment by aoberoi** [comment] 2018-04-18 23:07
it looks like the OP in #527 also had a similar issue with `KeepAlive` as demonstrated in the last log and stacktrace. i'd like to combine these two issues since they seem related.

**Comment by aoberoi** [comment] 2018-04-27 16:16
we think v4.2.0 fixes this issue. please update and give it a try! if not' feel free to comment and we'll reopen.

**Closed by aoberoi** 2018-04-27 16:16 UTC
Labels: bug

**Comment by aoberoi** [comment] 2018-05-01 15:35
@malonecm have you tried v4.2.0? Any better than the previous version? At the very least, we should have more meaningful logs now.

**Comment by malonecm** [comment] 2018-05-01 15:56
Yeah, I did upgrade. I have no seen any further crashes. I do still have debug logging on. If I see anything I will let you guys know!

**Comment by markspolakovs** [comment] 2019-08-15 21:22
I'm seeing this again now. `@slack/rtm-api` version 5.0.2, Ubuntu 19.04 (`Linux marksdesktop2-lin 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`). Here's a stack trace:

```
UnhandledPromiseRejectionWarning: Error: Unhandled event 'start' in state 'connecting'.
    at StateMachine.handleUnhandledEvent (/home/marks/code/bot-farm/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /home/marks/code/bot-farm/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/home/marks/code/bot-farm/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/home/marks/code/bot-farm/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/home/marks/code/bot-farm/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at RTMClient.start (/home/marks/code/bot-farm/node_modules/@slack/rtm-api/src/RTMClient.ts:382:23)
    at SlackRTMProvider.<anonymous> (/home/marks/code/bot-farm/src/providers/slack-rtm.ts:16:33)
    at Generator.next (<anonymous>)
    at /home/marks/code/bot-farm/src/providers/slack-rtm.ts:16:71
    at new Promise (<anonymous>)
    at __awaiter (/home/marks/code/bot-farm/src/providers/slack-rtm.ts:12:12)
    at SlackRTMProvider.connect (/home/marks/code/bot-farm/src/providers/slack-rtm.ts:31:16)
    at CBF.<anonymous> (/home/marks/code/bot-farm/src/providers/cbf.ts:453:34)
    at Generator.next (<anonymous>)
    at /home/marks/code/bot-farm/src/providers/cbf.ts:16:71
    at new Promise (<anonymous>)
    at __awaiter (/home/marks/code/bot-farm/src/providers/cbf.ts:12:12)
    at CBF.create (/home/marks/code/bot-farm/src/providers/cbf.ts:287:16)
    at Object.<anonymous> (/home/marks/code/bot-farm/src/bots/slash-vote/index.ts:16:40)
    at Generator.next (<anonymous>)
    at /home/marks/code/bot-farm/src/bots/slash-vote/index.ts:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/marks/code/bot-farm/src/bots/slash-vote/index.ts:3:12)
    at /home/marks/code/bot-farm/src/bots/slash-vote/index.ts:15:16
    at /home/marks/code/bot-farm/src/index.ts:72:5
    at Generator.next (<anonymous>)
    at fulfilled (/home/marks/code/bot-farm/src/index.ts:4:58)
```

**Comment by geoguide** [comment] 2022-12-05 16:08
Not sure if this is the same reason but same crash on @slack in socket mode.

```
/Users/me/Development/slackbot-mine/node_modules/finity/lib/core/StateMachine.js:76
      throw new Error('Unhandled event \'' + event + '\' in state \'' + this.currentState + '\'.');
            ^
Error: Unhandled event 'websocket open' in state 'connected'.
    at StateMachine.handleUnhandledEvent (/Users/me/Development/slackbot-mine/node_modules/finity/lib/core/StateMachine.js:76:13)
    at /Users/me/Development/slackbot-mine/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33
    at TaskScheduler.execute (/Users/me/Development/slackbot-mine/node_modules/finity/lib/core/TaskScheduler.js:29:7)
    at TaskScheduler.enqueue (/Users/me/Development/slackbot-mine/node_modules/finity/lib/core/TaskScheduler.js:19:12)
    at HierarchicalStateMachine.handle (/Users/me/Development/slackbot-mine/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24)
    at WebSocket.<anonymous> (/Users/me/Development/slackbot-mine/node_modules/@slack/socket-mode/src/SocketModeClient.ts:523:25)
    at WebSocket.onOpen (/Users/me/Development/slackbot-mine/node_modules/ws/lib/event-target.js:144:16)
    at WebSocket.emit (node:events:513:28)
    at WebSocket.emit (node:domain:489:12)
    at WebSocket.setSocket (/Users/me/Development/slackbot-mine/node_modules/ws/lib/websocket.js:225:10)
```

**Comment by nazmariam** [comment] 2023-06-15 09:17
Hello, we also faced the issue

logs: 
```
Going to establish a new connection to Slack ...
Reconnecting to Slack ...
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Unhandled event 'server disconnect old socket' in state 'connecting'. at StateMachine.handleUnhandledEvent (/app/node_modules/finity/lib/core/StateMachine.js:76:13) at /app/node_modules/finity/lib/core/HierarchicalStateMachine.js:79:33 at TaskScheduler.execute (/app/node_modules/finity/lib/core/TaskScheduler.js:29:7) at TaskScheduler.enqueue (/app/node_modules/finity/lib/core/TaskScheduler.js:19:12) at HierarchicalStateMachine.handle (/app/node_modules/finity/lib/core/HierarchicalStateMachine.js:72:24) at SocketModeClient.onWebSocketMessage (/app/node_modules/@slack/socket-mode/dist/SocketModeClient.js:579:31) at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:132:16) at WebSocket.emit (node:events:513:28) at WebSocket.emit (node:domain:489:12) at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1059:20)
```

**Comment by jwoo0122** [comment] 2024-04-05 17:05
We are facing this issue recently, too. Is there any updates or workaround to surpress this error?
