### ISSUE TITLE
Heroku memory usage increases suddenly until the dyno crashes

### ISSUE THREAD

**Issue by LaurentVB** [slackapi/node-slack-sdk#592] opened 2018-07-07 13:54 UTC
### Description

I recently upgraded from v3 to v4 and my heroku dyno started to randomly crash because of sudden spikes of memory usage.

Unfortunately, I could not replicate it locally :(
The server memory increases so quickly that logging stops immediately and I couldn't take a heap dump or anything to analyze where this comes from. It happens completely randomly.
I have experienced the issue with versions 4.1.0 and 4.3.1.

Reverting to v3 of the library prevents the issue from happening.

Sorry I couldn't give you any more information. If you have any suggestion on how I could gather more information on our production server, I'm very interested.

The symptoms here look like #529 but in my case, I verified that the issue is really linked to the usage of the v4 of this library.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.1.0, 4.3.1

node version: 8

OS version(s): Ubuntu 16.04 (heroku-16 stack)

#### Steps to reproduce:

1. sorry, no scenario. I only use the `WebClient.chat.postMessage` method though
2.
3.

#### Expected result:

The library does not increase memory usage in unmanageable ways

#### Actual result:

Memory usage skyrockets and the servers crashes as a result

#### Attachments:

<img width="1158" alt="screen shot 2018-07-05 at 15 21 55" src="https://user-images.githubusercontent.com/2806149/42386651-604f23e0-8140-11e8-8351-1f88ba992105.png">

**Comment by aoberoi** [comment] 2018-07-23 20:41
@LaurentVB thanks for communicating this issue with us. i appreciate that you tried to gather data and reproduction scenarios. memory issues for libraries can be very tricky.

i want to make sure i'm understanding one thing correctly: you are running the same exact application and just swapping the v3.x SDK for the v4.x SDK, and the result is that the v4.x SDK spikes memory usage so much more that it causes crashes on Heroku. that also means you did not add or remove any functionality in the app, so these two scenarios are roughly comparable. is that right?

if so, i think the next step here would be asking you to share a similar memory graph as the image above (so running the exact same calls API calls with the same or similar data if possible) but using the v3.x SDK. that way we can make a determination of how much worse the v4.x SDK is performing from a memory consumption POV.

as far as i can tell, this is not a leak, because it seems that the memory usage does return back to its equilibrium after a spike. rather, it seems this is an issue with a specific call stack running very expensive on memory.

what we  may be able to do in the meantime is try to reproduce these results using a simple app that just uses `WebClient#chat.postMessage()` to verify the problem exists and is understood, but i'd appreciate your help in first measuring how great a gap it is that we're trying to cover, as described above.

thanks!

**Comment by aoberoi** [comment] 2018-08-07 22:43
i've been trying to reproduce this issue and haven't yet been able to find a reason for the memory spike.

here is the entirety of my test application:

```javascript
const { createServer } = require('http');
const { WebClient } = require('@slack/client');

const slack = new WebClient(process.env.SLACK_TOKEN);

const server = createServer((req, res) => {
  slack.chat.postMessage({ channel: 'C72V3BUG5', text: 'Hello world' })
    .then(console.log)
    .catch(console.error);
  res.writeHead(200, { 'Content-Type': 'text/plain' });
  res.end('ok');
});

server.listen(process.env.PORT);
```

as you can see, i'm also just using `chat.postMessage`. each time a request comes into my server, i invoke it once. i hosted this application on Heroku and used node v8 so we can compare apples to apples. here's my memory usage graph:

<img width="255" alt="screen shot 2018-08-07 at 3 22 55 pm" src="https://user-images.githubusercontent.com/494795/43805820-1cb16e84-9a56-11e8-94cf-d9d39e49bc3b.png">

it looks like my apps steady state resident memory is about 14MB, and while i sent about 30 concurrent requests (so about 30 calls to `chat.postMessage` were in flight at about the same time), the memory usage topped at around 16MB. i think these are totally reasonable results.

since this is so wildly different than what you found, can you help us understand more details about how your app is behaving?

**Comment by aoberoi** [comment] 2018-08-20 17:15
Thanks for updating us @LaurentVB. I'll close this issue now so it doesn't distract us in the meantime. If you do find a reproduction case, feel free to keep commenting here, or create a new issue (mentioning this one).

**Closed by aoberoi** 2018-08-20 17:15 UTC
Labels: area:performance, enhancement, needs feedback
