### ISSUE TITLE
SlackEventAdapter does not have type 'on'

### ISSUE THREAD

**Issue by andrewyalung** [slackapi/node-slack-sdk#948] opened 2020-01-28 21:16 UTC
### Description

I'm attempting to switch to using `@slack/events-api` with TypeScript and seem to be running into an error that is stating `Property 'on' does not exist on type 'SlackEventAdapter'` when trying to set up the event handling.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [x] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [x] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 2.3.1

node version: 12.13.1

OS version(s): Mac OSX

#### Steps to reproduce:

1. import createEventAdapter using `import { createEventAdapter } from '@slack/events-api'`
2. set up the createEventAdapter using `const adapter = createEventAdapter(signingSecret)`
3. type `adapter.on('link_shared', (event) => console.log(event))` and see the typescript error

#### Attachments:
<img width="654" alt="Screen Shot 2020-01-28 at 1 10 00 PM" src="https://user-images.githubusercontent.com/50601399/73306141-6dd68600-41d0-11ea-9a56-31e5c899d3a4.png">

**Comment by jwulf** [comment] 2020-02-05 06:58
Here is my workaround atm: 

```
const slackEvents: SlackEventAdapter & EventEmitter = createEventAdapter(
  slackSigningSecret
) as any;
```

**Comment by jwulf** [comment] 2020-02-12 01:20
This is due to a change in the types for Node 13 (see [here](https://github.com/electron/electron/issues/21612#issuecomment-568691944)). Installing `@types/node@12.7.0` in my project fixes this for me.

**Comment by net8floz** [comment] 2020-03-01 21:07
would love a fix for this. I see there's a PR in another issue that fixes this. The issue is that event emitter and http have no default import. The PR looks like it just needs a reviewer to approve it. Thanks for the work on this repo.

**Comment by stevengill** [comment] 2020-03-02 21:28
@net8floz you are right. I believe https://github.com/slackapi/node-slack-sdk/pull/958 fixed this problem. I'm going to close this issue and aim to get a release out today/tomorrow with the fix.

**Closed** 2020-03-02 21:32 UTC
Labels: pkg:events-api

**Comment by garyposter** [comment] 2020-08-12 03:34
I'm on node 14 and seeing this. Is there a fix planned before Node 14 becomes current, October 20? Or perhaps this is unique to me?

**Comment by saini-g** [comment] 2020-12-07 12:25
I'm also facing this problem and installed the `@types/node@12.7.0` package as a dev dependency to get rid of the error.
Is there any plan to fix the problem for the latest node type definitions??
