### ISSUE TITLE
404 when attempting to use sendMessage in RTMClient

### ISSUE THREAD

**Issue by thepont** [slackapi/node-slack-sdk#978] opened 2020-03-25 04:16 UTC
### Description

Issue when sending messages using the `rtm.start()` function. 404 being raised.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

As of yesterday the rtm-client seems `@slack/rtm-api` seems to be returning a 404 each time it attempts to connect to slack.

```
const {RTMClient} = require('@slack/rtm-api');
const rtm = new RTMClient(SLACK_TOKEN);
rtm.start();
```

#### Packages:

Select all that apply:

- [ ] `@slack/web-api`
- [ ] `@slack/events-api`
- [ ] `@slack/interactive-messages`
- [x] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [ ] I don't know

#### Reproducible in:

package version: 5.0.3

node version: 10.15.3

OS version(s): Linux

#### Steps to reproduce:

Run the following code.

```
const {RTMClient} = require('@slack/rtm-api');
const rtm = new RTMClient(SLACK_TOKEN);
rtm.start();
```

#### Expected result:

Expect for us to be able to use the RTMClient

#### Actual result:

404 is raised.

```
[ERROR]  RTMClient:1 A websocket error occurred: Unexpected server response: 404
[ERROR]  RTMClient:1 A websocket error occurred: Unexpected server response: 404
```

**Comment by seratch** [comment] 2020-03-26 08:23
@thepont Hello, I tried to reproduce your issue but I haven't managed to see the same situation yet. Are you still facing the issue?

**Comment by thepont** [comment] 2020-03-26 08:59
Hey, I am currently still seeing it

**Comment by seratch** [comment] 2020-03-26 09:07
@thepont 
If you don't mind it, could you submit an inquiry to our customer support team from [here](https://slack.com/help/requests/new)? Our support agents can do a deeper and specific investigation with the information about your apps and workspaces.

My understanding so far is that your issue is not caused by this SDK, but some other factors or possibly our server-side issues. That said, if you give us some hints to simply reproduce your issue on my end, I'm happy to help you.

**Comment by piyushgupta27** [comment] 2020-03-27 15:21
I am getting the same issue. Unfortunately, Slack Support team asked me to raise an issue here. 😞

**Comment by seratch** [comment] 2020-03-27 23:36
@piyushgupta27 OK, I'm here for you to figure out what the issue is, but I haven't reproduced the 404 errors yet. There may be a specific condition causing the situation.

**Comment by thepont** [comment] 2020-03-29 08:10
I don't know if this is useful, but support got me to use my token with this url  https://api.slack.com/methods/rtm.connect/test and it does work although I am assuming the .start calls more then just this.

**Comment by thepont** [comment] 2020-03-30 00:10
I also just got a message from slack support attempting to handball the issue over here, I understand this is quite frustrating @seratch, being unable to replicate and the bug definitely being introduced by a change upstream.

I have done further investigation today, and can confirm that the error is occurring when he SDK attempts to establish a connection to the websocket URI that is passed back from the connect or the start methods.

While at the same time I seem to be able to establish a connection to the same URIs using the WebSocket API that is available in Chrome and Firefox, So I assume there might be some implementation differences between these and the `ws` package.

the `ws` package is attempting to do a https get to the url provided when it fails.

I hope some of this is helpful, I'm going to leave this for today and perhaps take another look tomorrow, please advise if there is anything I can check.

**Comment by piyushgupta27** [comment] 2020-03-30 08:15
Adding debug logs from NodeJS SDK if this help.
[slack-oncall-error-logs.txt](https://github.com/slackapi/node-slack-sdk/files/4401562/slack-oncall-error-logs.txt)

**Comment by piyushgupta27** [comment] 2020-03-30 08:53
> I don't know if this is useful, but support got me to use my token with this url https://api.slack.com/methods/rtm.connect/test and it does work although I am assuming the .start calls more then just this.
> 
> I just tested and https://api.slack.com/methods/rtm.start/test works for me too

Same for me, infact this Test tool via slack webpage gives me the same response as node SDK. As soon as the rtm.start() call is initiated, the slack websocket backend responds with "Unexpected server response: 404"
This 404 disconnects the connection and the cycle keeps on going indefinitely till the Rate Limit is hit.

```
[DEBUG]  RTMClient:1 transitioning to state: connecting:authenticated
Started listening to DEV_TESTING oncall bot
[ERROR]  RTMClient:1 A websocket error occurred: Unexpected server response: 404
[DEBUG]  RTMClient:1 transitioning to state: reconnecting
[DEBUG]  KeepAlive:0 stop monitoring
[DEBUG]  RTMClient:1 transitioning to state: connecting
[DEBUG]  RTMClient:1 transitioning to state: connecting:authenticating
[DEBUG]  WebClient:0 apiCall('rtm.connect') start
[DEBUG]  WebClient:0 will perform http request
```

**Comment by piyushgupta27** [comment] 2020-03-30 12:32
> I also just got a message from slack support attempting to handball the issue over here, I understand this is quite frustrating @seratch, being unable to replicate and the bug definitely being introduced by a change upstream.
> 
> I have done further investigation today, and can confirm that the error is occurring when he SDK attempts to establish a connection to the websocket URI that is passed back from the connect or the start methods.
> 
> While at the same time I seem to be able to establish a connection to the same URIs using the WebSocket API that is available in Chrome and Firefox, So I assume there might be some implementation differences between these and the `ws` package.
> 
> the `ws` package is attempting to do a https get to the url provided when it fails.
> 
> I hope some of this is helpful, I'm going to leave this for today and perhaps take another look tomorrow, please advise if there is anything I can check.

I was able to replicate the same things as shared above. Found the issue in "ws" package to be happening on the below line.

```
  type: 'error',
  message: 'Unexpected server response: 404',
  error: Error: Unexpected server response: 404
    at ClientRequest.req.on (/Users/piyush/Workspace/hotstar/tata-oncall-slackbot/node_modules/ws/lib/websocket.js:542:5)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:534:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:421:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:280:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onread (net.js:638:20) }
```

**Comment by elbuo8** [comment] 2020-03-30 15:20
@piyushgupta27 @thepont are you guys deploying by any chance in Australia?

We are facing this same issue *exclusively* in AU.

**Comment by aoberoi** [comment] 2020-03-30 17:52
Hey folks, sorry you've all been having difficulty connecting to RTM. I'm working on identifying the issue and resolving it for you.

Can you share your resolved dependency graphs with me? The easiest way to do this is to run `npm ls` inside your app, copy the output, and paste it in a comment here. If there's anything sensitive or private to your company in there, feel free to mask out the names of those things (replace them with `xxxxxxx` if you like). I'm most interested in seeing the version of dependencies of `@slack/rtm-api` like `ws`.

**Comment by aoberoi** [comment] 2020-03-30 18:20
We believe we've identified the issue on the Slack server side. I'll update this comment when the fix is rolled out.

**Comment by thepont** [comment] 2020-03-30 21:04
@aoberoi working for me now, thanks for all your help

**Comment by elbuo8** [comment] 2020-03-30 21:31
Working here too.

**Comment by piyushgupta27** [comment] 2020-03-31 06:07
@aoberoi Working for me too. Appreciate the fix!

**Comment by seratch** [comment] 2020-03-31 07:08
We're sorry for the errors and thank you very much for your patience. As it seems to be all good, please allow me to close this issue.

**Closed by seratch** 2020-03-31 07:08 UTC
Labels: bug, pkg:rtm-api
