### ISSUE TITLE
Better compatibility with source-map-support

### ISSUE THREAD

**Issue by gajus** [slackapi/node-slack-sdk#1120] opened 2020-11-20 15:38 UTC
### Description

At the moment NPM packages do not include `./src`.

```
ls -lah node_modules/@slack/web-api
total 48
drwxr-xr-x   5 gajus  staff    160 Oct 24 19:50 ./
drwxr-xr-x   5 gajus  staff    160 Oct 24 19:50 ../
-rw-r--r--   1 gajus  staff  17209 Oct 26  1985 README.md
drwxr-xr-x  34 gajus  staff   1088 Oct 24 19:50 dist/
-rw-r--r--   1 gajus  staff   3100 Oct 24 19:50 package.json

```

This is a problem, because if I get a stack trace such as the one below:

```
Error: A rate-limit has been reached, you may retry this request in 1 seconds
    at Object.rateLimitedErrorWithDelay (/Users/gajus/Documents/dev/[..]/node_modules/@slack/web-api/src/errors.ts:107:5)
    at /Users/gajus/Documents/dev/[..]/node_modules/@slack/web-api/src/WebClient.ts:323:36
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at run (/Users/gajus/Documents/dev/[..]/node_modules/p-queue/dist/index.js:163:29) {
  code: 'slack_webapi_rate_limited_error',
  retryAfter: 1
}

```

Then I cannot just click-through to the code to see what is causing the underlying issue.

**Comment by aoberoi** [comment] 2020-11-20 23:22
That's interesting. I would have thought the stack frames would reference files in `dist/`, which you should be able to click into. That may not be actually what you'd like, if you'd rather see the TypeScript input instead of the build output, but at least it would work. I'll try to reproduce this.

Are you interested in seeing the TypeScript source? If so, we'd need to make sure sourcemapping is wired up correctly and we'd need to ship the `src` directory in the distribution. This would be a tradeoff with bundle size. Are there any best practices for allowing smaller bundles as well as allowing folks to opt-in to the debugging with the source?

**Comment by aoberoi** [comment] 2020-11-21 01:13
I wasn't able to reproduce this problem. My stack trace is showing files in `dist`, and in the VSCode terminal, I can "click through" to the source file in `dist`.

![Kapture 2020-11-20 at 17 09 35](https://user-images.githubusercontent.com/494795/99863516-5ac3e680-2b53-11eb-838c-e1eee56c6838.gif)

Is there any other build tool processing your source code that might have contributed to this problem? Any info you can give us about your environment (node version, editor, etc)?

**Comment by gajus** [comment] 2020-11-22 16:58
The reason my stack trace includes `./src` is because `babel-node` uses https://www.npmjs.com/package/source-map-support. This automatically resolves stack trace to point to the original source codes.

**Comment by seratch** [comment] 2021-05-06 05:24
I've updated the labels for this task. Although our team is not actively working on this, contributions are always welcome (as long as it does not bring any breaking changes).

**Comment by sergio-toro** [comment] 2024-03-07 14:11
It's a shame that a company like Slack does not invest time in properly shipping SDK's...

**Comment by filmaj** [comment] 2024-06-05 18:00
I also cannot reproduce this error locally. Any suggestions on how to fix this issue; perhaps @sergio-toro you have a suggestion?

**Comment by filmaj** [comment] 2024-06-17 19:24
Going to close this issue as it is unclear to me what is broken / what needs fixing. If someone can provide that information, feel free to re-open / at-mention me!

**Closed by filmaj** 2024-06-17 19:24 UTC
Labels: needs info, pkg:web-api
