### ISSUE TITLE
handleMessageAck logs an error if sending message on RTM_CONNECTION_OPENED

### ISSUE THREAD

**Issue by mattlo** [slackapi/node-slack-sdk#253] opened 2016-07-21 17:49 UTC
If I try to send a message immediately after `RTM_CONNECTION_OPENED` event is emitted but before any presence or pings respond back, `_msgResponseHandlers` is empty which causes the client to log out an error: `message received with unknown reply_to:`

Logic causing this: https://github.com/slackhq/node-slack-sdk/blob/70255f200d9da6cb9b9644f77285a45bbdf7e99d/lib/clients/rtm/client.js#L487

This logic returns false if sending the message before a handler has been set but after the connection open is emitted.

To reproduce, I used to the document straight out of the README.md and the code from https://github.com/slackhq/node-slack-sdk/releases/tag/3.5.1

```
var RTM_CLIENT_EVENTS = require('@slack/client').CLIENT_EVENTS.RTM;

// you need to wait for the client to fully connect before you can send messages
rtm.on(RTM_CLIENT_EVENTS.RTM_CONNECTION_OPENED, function () {
  // This will send the message 'this is a test message' to the channel identified by id 'C0CHZA86Q'
  rtm.sendMessage('this is a test message', 'C0CHZA86Q', function messageSent() {
    // optionally, you can supply a callback to execute once the message has been sent
  });
});
```

**Comment by acrodrig** [comment] 2016-11-03 16:05
I am also being affected by this. @mattlo have you discovered any work arounds?

**Comment by aoberoi** [comment] 2016-11-15 23:54
this sounds like a duplicate of #251

**Closed** 2016-11-15 23:55 UTC
Labels: duplicate

**Comment by DEGoodmanWilson** [comment] 2016-12-01 19:45
Can y'all log the events you are receiving that triggers this behavior? Also, I am having a hard time seeing how `_msgResponseHandlers` would be _empty_—it seems more likely that the `reply_to` field in the received event is out of order, or perhaps even missing (`undefined`)?, which makes me think the cause might be something else…maybe. Anyway, it would be helpful to get some logging around this issue to help me diagnose it.
