### ISSUE TITLE
Receiving `user_not_found` error when calling `client.conversations.open` on a known user ID

### ISSUE THREAD

**Issue by jonesmo** [slackapi/node-slack-sdk#1705] opened 2023-12-14 21:27 UTC
#### Packages:

Select all that apply:

- [x] `@slack/web-api`
- [ ] `@slack/rtm-api`
- [ ] `@slack/webhooks`
- [x] `@slack/oauth`
- [ ] `@slack/socket-mode`
- [x] `@slack/types`
- [ ] I don't know

#### The Slack SDK version

"@slack/web-api": "^6.10.0"
"@slack/oauth": "^2.6.1"
"@slack/types": "^2.10.0"

#### Node.js runtime version

v18.17.1

#### OS info

ProductName:		macOS
ProductVersion:		14.2
BuildVersion:		23C64
Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64

#### Steps to reproduce:

1. Create a Slack app with the following OAuth permissions: channels:manage, channels:read, chat:write, groups:write, im:write, mpim:write, users:read, users:read.email.
2. Run `client.users.list()` and retrieve the user IDs for the Slack workspace
3. Using a retrieved user ID and the same client, run :
```
client.conversations.open({
      users: [userId],
      prevent_creation: false,
      text: 'Hi there.....',
    });
```

### Expected result:

I open a direct message with `userId` person that says "Hi there.....".

### Actual result:

I receive a `user_not_found` error:
```
Error: An API error occurred: user_not_found
    at platformErrorFromResult (/Users/mej/node_modules/.pnpm/@slack+web-api@6.10.0/node_modules/@slack/web-api/dist/errors.js:62:33)
    at WebClient.apiCall (/Users/mej/node_modules/.pnpm/@slack+web-api@6.10.0/node_modules/@slack/web-api/dist/WebClient.js:181:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async privateMessage (/Users/mej/apps/example-app/test_bot/test_bot.ts:22:5) {
  code: 'slack_webapi_platform_error',
  data: {
    ok: false,
    error: 'user_not_found',
    response_metadata: { scopes: [Array], acceptedScopes: [Array] }
  }
}
```

### Requirements

For general questions/issues about Slack API platform or its server-side, could you submit questions at https://my.slack.com/help/requests/new instead. :bow:

Please read the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment] 2023-12-14 21:33
hi, @jonesmo! Thank you for your question, and sorry to hear you're running into some trouble!

Looking at the provided code, there's a chance you're passing in the `users` property incorrectly. Based on [the documentation](https://api.slack.com/methods/conversations.open#arg_users), `users` in `conversations.open` needs to be a comma-separated string list of user IDs - it looks like you're passing in an array. Could you try converting this to a comma-separated string list and then passing it in to see if your API call is successful?

**Comment by jonesmo** [comment] 2023-12-14 21:46
Gotcha, thanks!  I replaced the array with a single user ID in quotes, and
it didn't throw an error, and it also didn't send private messages to the
two user IDs I tried.

**Comment by hello-ashleyintech** [comment] 2023-12-14 21:50
thanks for the update @jonesmo! Have you checked to make sure that the user IDs you're passing in correspond with valid user IDs in the workspace you're calling `conversations.open` in? that's strange that it returned no error but also didn't fulfill the expected behavior.

**Comment by jonesmo** [comment] 2023-12-14 21:55
I run `client.users.list()` and copy-paste user IDs directly from those results into `conversations.open()`.  I'm also seeing that 
```client.chat.postMessage({
      channel: '#bot-test',
      text: `The current time is ${currentTime}`,
    })```
returns a `channel_not_found` message even though it had no problems posting to that channel yesterday.  I don't know if that's related -- I figured I'd include that here in case it's helpful.

**Comment by jonesmo** [comment] 2023-12-18 20:41
I figured out the `channel_not_found` error; the bot must have been kicked out of the channel, maybe when I added some permissions and reinstalled it.  The problem still stands that it doesn't send private messages and doesn't throw an error.

**Comment by jonesmo** [comment] 2023-12-18 20:57
Here's what's returned by `client.conversations.open`:
```
{
  ok: true,
  no_op: true,
  already_open: true,
  channel: { id: 'DXXXXXXX' },
  response_metadata: {
    scopes: [
      'users:read',
      'users:read.email',
      'chat:write',
      'im:write',
      'channels:manage',
      'groups:write',
      'mpim:write',
      'channels:read'
    ],
    acceptedScopes: [
      'channels:write',
      'groups:write',
      'mpim:write',
      'im:write',
      'post'
    ]
  }
}
```

**Comment by jonesmo** [comment] 2023-12-18 21:12
Aha!  I did not realize that `client.conversations.open` wasn't the full command to send a direct message.  That was my problem.  Once I add `client.chat.postMessage` to the DM channel ID after the `client.conversations.open`, it works just fine.  It would be very helpful if that were added to the documentation for `client.conversations.open`.

**Comment by filmaj** [comment] 2023-12-19 14:55
I believe it is documented: https://api.slack.com/methods/conversations.open

Do you have a specific suggestion on what kind of change you would like to see, in order to make this clearer?

**Comment by hello-ashleyintech** [comment] 2023-12-20 16:43
Gotcha @jonesmo, thanks for clarifying! I'll pass this along to our docs team and let them know about this suggestion! 🙌

**Comment by hello-ashleyintech** [comment] 2023-12-21 15:48
hey, @jonesmo! we were able to get the docs updated with your suggested changes! you can find it [here](https://api.slack.com/methods/conversations.open) under the "Usage" section. 🎉 

I'm going to close this issue out since it seems to be resolved now, but feel free to submit a new issue if you have any additional questions! 😄

**Closed by hello-ashleyintech** 2023-12-21 15:48 UTC
Labels: question

**Comment by jonesmo** [comment] 2023-12-21 18:51
This is so helpful!  I really appreciate it!  Hope it helps future users.
