### ISSUE TITLE
Media is not being 'unfurled' in ephemeral messages

### ISSUE THREAD

**Issue by madltd** [slackapi/node-slack-sdk#614] opened 2018-08-12 04:33 UTC
### Description

Describe your issue here.

### What type of issue is this?
- [x] bug
- [ ] enhancement (feature request)
- [x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements
* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/node-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

Filling out the following details about bugs will help us solve your issue sooner.

#### Reproducible in:

`@slack/client` version: 4.4.0

node version: 10.2.1

Calling
```ts
webClient.chat.postEphemeral(message: ChatPostEphemeralArguments);
```
Does not unfurl any links or media even when.
```ts
// message
unfurl_links: true,
unfurl_media: true,
// message
```

It only unfurls images in attachments but I need to make it unfurl youtube videos (in ephemeral, for `.postMessage()` it works well)
Tried setting either of them to true, does not work.

Is it meant to work? How can I make it work?

**Comment by aoberoi** [comment] 2018-08-12 18:05
@madltd The `unfurl_links` and `unfurl_media` arguments are not valid for [`chat.postEphemeral`](https://api.slack.com/methods/chat.postEphemeral). But I do think that links to YouTube media should unfurl automatically. I'll investigate whether this is a bug. Thanks for reporting.

**Comment by aoberoi** [comment] 2018-08-25 00:00
This is a confirmed bug in the Slack platform. It's not a bug we can fix from within the SDK, so I'll close this issue.

I don't have any workarounds for this issue at this time.

Internal Slack bug: `PAS-544`

**Closed by aoberoi** 2018-08-25 00:00 UTC
Labels: question

**Comment by sshantel** [comment] 2020-10-05 17:59
Hi there @aoberoi I'm having this same issue right now - the links are not unfurling and I have       `  response = client.chat_postMessage(channel=SLACK_CHANNEL, text=desc, unfurl_links=True, unfurl_media=True )
` Has there been any update on this since? Any insight would be appreciated. Thanks so much!
